# XAUUSD Trading Bot Configuration
import os

# Telegram Configuration (تم تحديث المسميات لتتوافق مع كود البوت)
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', os.getenv('TELEGRAM_TOKEN', '8858345146:AAGPy6Qxtr5k0EV3P_nvCXPaL1aaP_yA5no'))
TELEGRAM_TOKEN = TELEGRAM_BOT_TOKEN
BOT_TOKEN = TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '8952278702')

# Exchange Configuration
EXCHANGE_ID = os.getenv('EXCHANGE_ID', 'binance')
SYMBOL = os.getenv('SYMBOL', 'XAU/USD:XAU')

# BIQuote API Configuration
BIQUOTE_BASE_URL = os.getenv('BIQUOTE_BASE_URL', 'https://biquote.io/api')
BIQUOTE_SYMBOL = os.getenv('BIQUOTE_SYMBOL', 'XAUUSD')
XAUUSD_SOURCE = os.getenv('XAUUSD_SOURCE', 'BIQUOTE')

# Trading Parameters
TIMEFRAMES = ['1m', '5m', '15m', '30m', '1h', '4h']
CANDLES_COUNT = 600

# Technical Indicators Settings
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

BOLLINGER_PERIOD = 20
BOLLINGER_STD = 2

SMA_PERIODS = [50, 100, 200]
EMA_PERIODS = [20, 50]

# Signal Strength Thresholds
STRONG_BUY_THRESHOLD = 0.7
STRONG_SELL_THRESHOLD = 0.7

# Risk Management
RISK_PER_TRADE = 0.02
STOP_LOSS_ATR_MULTIPLIER = 1.25
TAKE_PROFIT_ATR_MULTIPLIER = 1.0
TP1_ATR_MULTIPLIER = 1.0
TP2_ATR_MULTIPLIER = 1.5
TP3_ATR_MULTIPLIER = 2.0

# API Rate Limits
RATE_LIMIT_DELAY = 0.1

# Bot Settings
BOT_NAME = "XAUUSD Trading Bot"
BOT_VERSION = "1.0.0"
CHECK_INTERVAL = 1
DECISION_CANDLES = 50
ACTIVE_SIGNAL_TIMEOUT_HOURS = 24

# Logging
LOG_LEVEL = 'INFO'
LOG_FILE = 'bot.log'

# Render/Deployment Settings
PORT = int(os.getenv('PORT', 10000))
WEB_SERVER_ENABLED = True
